'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
'
Namespace com.infinishops.io
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IShopServiceActivationSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IShopServiceActivation
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnabledServicesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://io.infinishops.com/services/IShopServiceActivation.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnabledServicesCompleted As EnabledServicesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnabledServices", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnabledServices(ByVal info As ServiceInfo) As EnabledServicesResult
            Dim results() As Object = Me.Invoke("EnabledServices", New Object() {info})
            Return CType(results(0),EnabledServicesResult)
        End Function
        
        '''<remarks/>
        Public Function BeginEnabledServices(ByVal info As ServiceInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EnabledServices", New Object() {info}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndEnabledServices(ByVal asyncResult As System.IAsyncResult) As EnabledServicesResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EnabledServicesResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnabledServicesAsync(ByVal info As ServiceInfo)
            Me.EnabledServicesAsync(info, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnabledServicesAsync(ByVal info As ServiceInfo, ByVal userState As Object)
            If (Me.EnabledServicesOperationCompleted Is Nothing) Then
                Me.EnabledServicesOperationCompleted = AddressOf Me.OnEnabledServicesOperationCompleted
            End If
            Me.InvokeAsync("EnabledServices", New Object() {info}, Me.EnabledServicesOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnabledServicesOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnabledServicesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnabledServicesCompleted(Me, New EnabledServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiceInfo
        
        Private merchantIDField As String
        
        Private customerIDField As String
        
        Private orderIDField As String
        
        Private isOrderSuccessField As Boolean
        
        Private payModeField As PaymentMode
        
        Private dotNotSendDeclineEmailField As Boolean
        
        '''<remarks/>
        Public Property MerchantID() As String
            Get
                Return Me.merchantIDField
            End Get
            Set
                Me.merchantIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerID() As String
            Get
                Return Me.customerIDField
            End Get
            Set
                Me.customerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderID() As String
            Get
                Return Me.orderIDField
            End Get
            Set
                Me.orderIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsOrderSuccess() As Boolean
            Get
                Return Me.isOrderSuccessField
            End Get
            Set
                Me.isOrderSuccessField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PayMode() As PaymentMode
            Get
                Return Me.payModeField
            End Get
            Set
                Me.payModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DotNotSendDeclineEmail() As Boolean
            Get
                Return Me.dotNotSendDeclineEmailField
            End Get
            Set
                Me.dotNotSendDeclineEmailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum PaymentMode
        
        '''<remarks/>
        CC
        
        '''<remarks/>
        CB
        
        '''<remarks/>
        BP
        
        '''<remarks/>
        PA
        
        '''<remarks/>
        CR
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnabledServicesResult
        
        Private eRRORCODEField As String
        
        Private eRRORDESCField As String
        
        '''<remarks/>
        Public Property ERRORCODE() As String
            Get
                Return Me.eRRORCODEField
            End Get
            Set
                Me.eRRORCODEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ERRORDESC() As String
            Get
                Return Me.eRRORDESCField
            End Get
            Set
                Me.eRRORDESCField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub EnabledServicesCompletedEventHandler(ByVal sender As Object, ByVal e As EnabledServicesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnabledServicesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EnabledServicesResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EnabledServicesResult)
            End Get
        End Property
    End Class
End Namespace
