'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace InfiniPaypal
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="InfiniPayPalWebServiceSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AbstractResponseType))>  _
    Public Class InfiniPayPalWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://paypalgate.infinishops.com/InfiniPayPalWebService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MakeTransaction", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MakeTransaction(ByVal paypaID As String, ByVal paypalPassword As String, ByVal Envoirement As String, ByVal cardNumber As String, ByVal cardType As Integer, ByVal CVV2 As String, ByVal endMonth As String, ByVal endYear As String, ByVal totalAmount As String, ByVal moneyType As String, ByVal invoiceID As String, ByRef code As String, ByRef msg As String) As String
            Dim results() As Object = Me.Invoke("MakeTransaction", New Object() {paypaID, paypalPassword, Envoirement, cardNumber, cardType, CVV2, endMonth, endYear, totalAmount, moneyType, invoiceID, code, msg})
            code = CType(results(1),String)
            msg = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginMakeTransaction(ByVal paypaID As String, ByVal paypalPassword As String, ByVal Envoirement As String, ByVal cardNumber As String, ByVal cardType As Integer, ByVal CVV2 As String, ByVal endMonth As String, ByVal endYear As String, ByVal totalAmount As String, ByVal moneyType As String, ByVal invoiceID As String, ByVal code As String, ByVal msg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MakeTransaction", New Object() {paypaID, paypalPassword, Envoirement, cardNumber, cardType, CVV2, endMonth, endYear, totalAmount, moneyType, invoiceID, code, msg}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndMakeTransaction(ByVal asyncResult As System.IAsyncResult, ByRef code As String, ByRef msg As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            code = CType(results(1),String)
            msg = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MakeTransaction_Overleaded", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MakeTransaction_Overleaded( _
                    ByVal paypaID As String,  _
                    ByVal paypalPassword As String,  _
                    ByVal Envoirement As String,  _
                    ByVal cardNumber As String,  _
                    ByVal cardType As Integer,  _
                    ByVal CVV2 As String,  _
                    ByVal endMonth As String,  _
                    ByVal endYear As String,  _
                    ByVal totalAmount As String,  _
                    ByVal moneyType As String,  _
                    ByVal invoiceID As String,  _
                    ByRef code As String,  _
                    ByRef msg As String,  _
                    ByVal FirstName As String,  _
                    ByVal Lastname As String,  _
                    ByVal City As String,  _
                    ByVal Street As String,  _
                    ByVal State As String,  _
                    ByVal PostCode As String,  _
                    ByVal CountryCode As String) As String
            Dim results() As Object = Me.Invoke("MakeTransaction_Overleaded", New Object() {paypaID, paypalPassword, Envoirement, cardNumber, cardType, CVV2, endMonth, endYear, totalAmount, moneyType, invoiceID, code, msg, FirstName, Lastname, City, Street, State, PostCode, CountryCode})
            code = CType(results(1),String)
            msg = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginMakeTransaction_Overleaded( _
                    ByVal paypaID As String,  _
                    ByVal paypalPassword As String,  _
                    ByVal Envoirement As String,  _
                    ByVal cardNumber As String,  _
                    ByVal cardType As Integer,  _
                    ByVal CVV2 As String,  _
                    ByVal endMonth As String,  _
                    ByVal endYear As String,  _
                    ByVal totalAmount As String,  _
                    ByVal moneyType As String,  _
                    ByVal invoiceID As String,  _
                    ByVal code As String,  _
                    ByVal msg As String,  _
                    ByVal FirstName As String,  _
                    ByVal Lastname As String,  _
                    ByVal City As String,  _
                    ByVal Street As String,  _
                    ByVal State As String,  _
                    ByVal PostCode As String,  _
                    ByVal CountryCode As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MakeTransaction_Overleaded", New Object() {paypaID, paypalPassword, Envoirement, cardNumber, cardType, CVV2, endMonth, endYear, totalAmount, moneyType, invoiceID, code, msg, FirstName, Lastname, City, Street, State, PostCode, CountryCode}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndMakeTransaction_Overleaded(ByVal asyncResult As System.IAsyncResult, ByRef code As String, ByRef msg As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            code = CType(results(1),String)
            msg = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExpressCheckout", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExpressCheckout(ByVal paypalID As String, ByVal paypalPassword As String, ByVal Envoironment As String, ByVal PaymentAmount As String, ByVal CurrencyCode As String, ByVal ReturnURL As String, ByVal CancelURL As String) As SetExpressCheckoutResponseType
            Dim results() As Object = Me.Invoke("ExpressCheckout", New Object() {paypalID, paypalPassword, Envoironment, PaymentAmount, CurrencyCode, ReturnURL, CancelURL})
            Return CType(results(0),SetExpressCheckoutResponseType)
        End Function
        
        '<remarks/>
        Public Function BeginExpressCheckout(ByVal paypalID As String, ByVal paypalPassword As String, ByVal Envoironment As String, ByVal PaymentAmount As String, ByVal CurrencyCode As String, ByVal ReturnURL As String, ByVal CancelURL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ExpressCheckout", New Object() {paypalID, paypalPassword, Envoironment, PaymentAmount, CurrencyCode, ReturnURL, CancelURL}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndExpressCheckout(ByVal asyncResult As System.IAsyncResult) As SetExpressCheckoutResponseType
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SetExpressCheckoutResponseType)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCheckoutDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCheckoutDetails(ByVal paypalID As String, ByVal paypalPassword As String, ByVal Envoironment As String, ByVal token As String) As GetExpressCheckoutDetailsResponseType
            Dim results() As Object = Me.Invoke("GetCheckoutDetails", New Object() {paypalID, paypalPassword, Envoironment, token})
            Return CType(results(0),GetExpressCheckoutDetailsResponseType)
        End Function
        
        '<remarks/>
        Public Function BeginGetCheckoutDetails(ByVal paypalID As String, ByVal paypalPassword As String, ByVal Envoironment As String, ByVal token As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCheckoutDetails", New Object() {paypalID, paypalPassword, Envoironment, token}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetCheckoutDetails(ByVal asyncResult As System.IAsyncResult) As GetExpressCheckoutDetailsResponseType
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetExpressCheckoutDetailsResponseType)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DOExpressCheckoutFinal", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DOExpressCheckoutFinal(ByVal paypalID As String, ByVal paypalPassword As String, ByVal Envoirement As String, ByVal Token As String, ByVal PayerID As String, ByVal PaymentAmount As String, ByVal PaymentAction As PaymentActionCodeType, ByVal CurrencyCode As CurrencyCodeType) As DoExpressCheckoutPaymentResponseType
            Dim results() As Object = Me.Invoke("DOExpressCheckoutFinal", New Object() {paypalID, paypalPassword, Envoirement, Token, PayerID, PaymentAmount, PaymentAction, CurrencyCode})
            Return CType(results(0),DoExpressCheckoutPaymentResponseType)
        End Function
        
        '<remarks/>
        Public Function BeginDOExpressCheckoutFinal(ByVal paypalID As String, ByVal paypalPassword As String, ByVal Envoirement As String, ByVal Token As String, ByVal PayerID As String, ByVal PaymentAmount As String, ByVal PaymentAction As PaymentActionCodeType, ByVal CurrencyCode As CurrencyCodeType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DOExpressCheckoutFinal", New Object() {paypalID, paypalPassword, Envoirement, Token, PayerID, PaymentAmount, PaymentAction, CurrencyCode}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDOExpressCheckoutFinal(ByVal asyncResult As System.IAsyncResult) As DoExpressCheckoutPaymentResponseType
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DoExpressCheckoutPaymentResponseType)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InstallCertificate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InstallCertificate(ByVal MIDentity As String, ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Certificate() As Byte) As String
            Dim results() As Object = Me.Invoke("InstallCertificate", New Object() {MIDentity, password, Certificate})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginInstallCertificate(ByVal MIDentity As String, ByVal password As String, ByVal Certificate() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("InstallCertificate", New Object() {MIDentity, password, Certificate}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndInstallCertificate(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsCertificatInstalled", RequestElementName:="IsCertificatInstalled", RequestNamespace:="http://tempuri.org/", ResponseElementName:="IsCertificatInstalledResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ISCertInstalled(ByVal paypaID As String, ByVal paypalPassword As String, ByVal Envoirement As String) As <System.Xml.Serialization.XmlElementAttribute("IsCertificatInstalledResult")> Integer
            Dim results() As Object = Me.Invoke("ISCertInstalled", New Object() {paypaID, paypalPassword, Envoirement})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginISCertInstalled(ByVal paypaID As String, ByVal paypalPassword As String, ByVal Envoirement As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ISCertInstalled", New Object() {paypaID, paypalPassword, Envoirement}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndISCertInstalled(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class SetExpressCheckoutResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        Public Token As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(MassPayResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SetExpressCheckoutResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DoDirectPaymentResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BillUserResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BAUpdateResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DoAuthorizationResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetExpressCheckoutDetailsResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DoExpressCheckoutPaymentResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TransactionSearchResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(RefundTransactionResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetTransactionDetailsResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EnterBoardingResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AddressVerifyResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DoCaptureResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetMobileStatusResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DoReauthorizationResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DoVoidResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CreateMobilePaymentResponseType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetBoardingDetailsResponseType))>  _
    Public MustInherit Class AbstractResponseType
        
        '<remarks/>
        Public Timestamp As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public TimestampSpecified As Boolean
        
        '<remarks/>
        Public Ack As AckCodeType
        
        '<remarks/>
        Public CorrelationID As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Errors")>  _
        Public Errors() As ErrorType
        
        '<remarks/>
        Public Version As String
        
        '<remarks/>
        Public Build As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Any As System.Xml.XmlElement
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum AckCodeType
        
        '<remarks/>
        Success
        
        '<remarks/>
        Failure
        
        '<remarks/>
        Warning
        
        '<remarks/>
        SuccessWithWarning
        
        '<remarks/>
        FailureWithWarning
        
        '<remarks/>
        CustomCode
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class ErrorType
        
        '<remarks/>
        Public ShortMessage As String
        
        '<remarks/>
        Public LongMessage As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")>  _
        Public ErrorCode As String
        
        '<remarks/>
        Public SeverityCode As SeverityCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ErrorParameters")>  _
        Public ErrorParameters() As ErrorParameterType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum SeverityCodeType
        
        '<remarks/>
        Warning
        
        '<remarks/>
        [Error]
        
        '<remarks/>
        CustomCode
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class ErrorParameterType
        
        '<remarks/>
        Public Value As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public ParamID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class MerchantPullPaymentResponseType
        
        '<remarks/>
        Public PayerInfo As PayerInfoType
        
        '<remarks/>
        Public PaymentInfo As PaymentInfoType
        
        '<remarks/>
        Public MerchantPullInfo As MerchantPullInfoType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class PayerInfoType
        
        '<remarks/>
        Public Payer As String
        
        '<remarks/>
        Public PayerID As String
        
        '<remarks/>
        Public PayerStatus As PayPalUserStatusCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public PayerStatusSpecified As Boolean
        
        '<remarks/>
        Public PayerName As PersonNameType
        
        '<remarks/>
        Public PayerCountry As CountryCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public PayerCountrySpecified As Boolean
        
        '<remarks/>
        Public PayerBusiness As String
        
        '<remarks/>
        Public Address As AddressType
        
        '<remarks/>
        Public ContactPhone As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum PayPalUserStatusCodeType
        
        '<remarks/>
        verified
        
        '<remarks/>
        unverified
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class PersonNameType
        
        '<remarks/>
        Public Salutation As String
        
        '<remarks/>
        Public FirstName As String
        
        '<remarks/>
        Public MiddleName As String
        
        '<remarks/>
        Public LastName As String
        
        '<remarks/>
        Public Suffix As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum CountryCodeType
        
        '<remarks/>
        AF
        
        '<remarks/>
        AL
        
        '<remarks/>
        DZ
        
        '<remarks/>
        [AS]
        
        '<remarks/>
        AD
        
        '<remarks/>
        AO
        
        '<remarks/>
        AI
        
        '<remarks/>
        AQ
        
        '<remarks/>
        AG
        
        '<remarks/>
        AR
        
        '<remarks/>
        AM
        
        '<remarks/>
        AW
        
        '<remarks/>
        AU
        
        '<remarks/>
        AT
        
        '<remarks/>
        AZ
        
        '<remarks/>
        BS
        
        '<remarks/>
        BH
        
        '<remarks/>
        BD
        
        '<remarks/>
        BB
        
        '<remarks/>
        BY
        
        '<remarks/>
        BE
        
        '<remarks/>
        BZ
        
        '<remarks/>
        BJ
        
        '<remarks/>
        BM
        
        '<remarks/>
        BT
        
        '<remarks/>
        BO
        
        '<remarks/>
        BA
        
        '<remarks/>
        BW
        
        '<remarks/>
        BV
        
        '<remarks/>
        BR
        
        '<remarks/>
        IO
        
        '<remarks/>
        BN
        
        '<remarks/>
        BG
        
        '<remarks/>
        BF
        
        '<remarks/>
        BI
        
        '<remarks/>
        KH
        
        '<remarks/>
        CM
        
        '<remarks/>
        CA
        
        '<remarks/>
        CV
        
        '<remarks/>
        KY
        
        '<remarks/>
        CF
        
        '<remarks/>
        TD
        
        '<remarks/>
        CL
        
        '<remarks/>
        CN
        
        '<remarks/>
        CX
        
        '<remarks/>
        CC
        
        '<remarks/>
        CO
        
        '<remarks/>
        KM
        
        '<remarks/>
        CG
        
        '<remarks/>
        CD
        
        '<remarks/>
        CK
        
        '<remarks/>
        CR
        
        '<remarks/>
        CI
        
        '<remarks/>
        HR
        
        '<remarks/>
        CU
        
        '<remarks/>
        CY
        
        '<remarks/>
        CZ
        
        '<remarks/>
        DK
        
        '<remarks/>
        DJ
        
        '<remarks/>
        DM
        
        '<remarks/>
        [DO]
        
        '<remarks/>
        TP
        
        '<remarks/>
        EC
        
        '<remarks/>
        EG
        
        '<remarks/>
        SV
        
        '<remarks/>
        GQ
        
        '<remarks/>
        ER
        
        '<remarks/>
        EE
        
        '<remarks/>
        ET
        
        '<remarks/>
        FK
        
        '<remarks/>
        FO
        
        '<remarks/>
        FJ
        
        '<remarks/>
        FI
        
        '<remarks/>
        FR
        
        '<remarks/>
        GF
        
        '<remarks/>
        PF
        
        '<remarks/>
        TF
        
        '<remarks/>
        GA
        
        '<remarks/>
        GM
        
        '<remarks/>
        GE
        
        '<remarks/>
        DE
        
        '<remarks/>
        GH
        
        '<remarks/>
        GI
        
        '<remarks/>
        GR
        
        '<remarks/>
        GL
        
        '<remarks/>
        GD
        
        '<remarks/>
        GP
        
        '<remarks/>
        GU
        
        '<remarks/>
        GT
        
        '<remarks/>
        GN
        
        '<remarks/>
        GW
        
        '<remarks/>
        GY
        
        '<remarks/>
        HT
        
        '<remarks/>
        HM
        
        '<remarks/>
        VA
        
        '<remarks/>
        HN
        
        '<remarks/>
        HK
        
        '<remarks/>
        HU
        
        '<remarks/>
        [IS]
        
        '<remarks/>
        [IN]
        
        '<remarks/>
        ID
        
        '<remarks/>
        IR
        
        '<remarks/>
        IQ
        
        '<remarks/>
        IE
        
        '<remarks/>
        IL
        
        '<remarks/>
        IT
        
        '<remarks/>
        JM
        
        '<remarks/>
        JP
        
        '<remarks/>
        JO
        
        '<remarks/>
        KZ
        
        '<remarks/>
        KE
        
        '<remarks/>
        KI
        
        '<remarks/>
        KP
        
        '<remarks/>
        KR
        
        '<remarks/>
        KW
        
        '<remarks/>
        KG
        
        '<remarks/>
        LA
        
        '<remarks/>
        LV
        
        '<remarks/>
        LB
        
        '<remarks/>
        LS
        
        '<remarks/>
        LR
        
        '<remarks/>
        LY
        
        '<remarks/>
        LI
        
        '<remarks/>
        LT
        
        '<remarks/>
        LU
        
        '<remarks/>
        MO
        
        '<remarks/>
        MK
        
        '<remarks/>
        MG
        
        '<remarks/>
        MW
        
        '<remarks/>
        MY
        
        '<remarks/>
        MV
        
        '<remarks/>
        ML
        
        '<remarks/>
        MT
        
        '<remarks/>
        MH
        
        '<remarks/>
        MQ
        
        '<remarks/>
        MR
        
        '<remarks/>
        MU
        
        '<remarks/>
        YT
        
        '<remarks/>
        MX
        
        '<remarks/>
        FM
        
        '<remarks/>
        MD
        
        '<remarks/>
        MC
        
        '<remarks/>
        MN
        
        '<remarks/>
        MS
        
        '<remarks/>
        MA
        
        '<remarks/>
        MZ
        
        '<remarks/>
        MM
        
        '<remarks/>
        NA
        
        '<remarks/>
        NR
        
        '<remarks/>
        NP
        
        '<remarks/>
        NL
        
        '<remarks/>
        AN
        
        '<remarks/>
        NC
        
        '<remarks/>
        NZ
        
        '<remarks/>
        NI
        
        '<remarks/>
        NE
        
        '<remarks/>
        NG
        
        '<remarks/>
        NU
        
        '<remarks/>
        NF
        
        '<remarks/>
        MP
        
        '<remarks/>
        NO
        
        '<remarks/>
        OM
        
        '<remarks/>
        PK
        
        '<remarks/>
        PW
        
        '<remarks/>
        PS
        
        '<remarks/>
        PA
        
        '<remarks/>
        PG
        
        '<remarks/>
        PY
        
        '<remarks/>
        PE
        
        '<remarks/>
        PH
        
        '<remarks/>
        PN
        
        '<remarks/>
        PL
        
        '<remarks/>
        PT
        
        '<remarks/>
        PR
        
        '<remarks/>
        QA
        
        '<remarks/>
        RE
        
        '<remarks/>
        RO
        
        '<remarks/>
        RU
        
        '<remarks/>
        RW
        
        '<remarks/>
        SH
        
        '<remarks/>
        KN
        
        '<remarks/>
        LC
        
        '<remarks/>
        PM
        
        '<remarks/>
        VC
        
        '<remarks/>
        WS
        
        '<remarks/>
        SM
        
        '<remarks/>
        ST
        
        '<remarks/>
        SA
        
        '<remarks/>
        SN
        
        '<remarks/>
        SC
        
        '<remarks/>
        SL
        
        '<remarks/>
        SG
        
        '<remarks/>
        SK
        
        '<remarks/>
        SI
        
        '<remarks/>
        SB
        
        '<remarks/>
        SO
        
        '<remarks/>
        ZA
        
        '<remarks/>
        GS
        
        '<remarks/>
        ES
        
        '<remarks/>
        LK
        
        '<remarks/>
        SD
        
        '<remarks/>
        SR
        
        '<remarks/>
        SJ
        
        '<remarks/>
        SZ
        
        '<remarks/>
        SE
        
        '<remarks/>
        CH
        
        '<remarks/>
        SY
        
        '<remarks/>
        TW
        
        '<remarks/>
        TJ
        
        '<remarks/>
        TZ
        
        '<remarks/>
        TH
        
        '<remarks/>
        TG
        
        '<remarks/>
        TK
        
        '<remarks/>
        [TO]
        
        '<remarks/>
        TT
        
        '<remarks/>
        TN
        
        '<remarks/>
        TR
        
        '<remarks/>
        TM
        
        '<remarks/>
        TC
        
        '<remarks/>
        TV
        
        '<remarks/>
        UG
        
        '<remarks/>
        UA
        
        '<remarks/>
        AE
        
        '<remarks/>
        GB
        
        '<remarks/>
        US
        
        '<remarks/>
        UM
        
        '<remarks/>
        UY
        
        '<remarks/>
        UZ
        
        '<remarks/>
        VU
        
        '<remarks/>
        VE
        
        '<remarks/>
        VN
        
        '<remarks/>
        VG
        
        '<remarks/>
        VI
        
        '<remarks/>
        WF
        
        '<remarks/>
        EH
        
        '<remarks/>
        YE
        
        '<remarks/>
        YU
        
        '<remarks/>
        ZM
        
        '<remarks/>
        ZW
        
        '<remarks/>
        AA
        
        '<remarks/>
        QM
        
        '<remarks/>
        QN
        
        '<remarks/>
        QO
        
        '<remarks/>
        QP
        
        '<remarks/>
        CS
        
        '<remarks/>
        CustomCode
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class AddressType
        
        '<remarks/>
        Public Name As String
        
        '<remarks/>
        Public Street1 As String
        
        '<remarks/>
        Public Street2 As String
        
        '<remarks/>
        Public CityName As String
        
        '<remarks/>
        Public StateOrProvince As String
        
        '<remarks/>
        Public Country As CountryCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public CountrySpecified As Boolean
        
        '<remarks/>
        Public CountryName As String
        
        '<remarks/>
        Public Phone As String
        
        '<remarks/>
        Public PostalCode As String
        
        '<remarks/>
        Public AddressID As String
        
        '<remarks/>
        Public AddressOwner As AddressOwnerCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public AddressOwnerSpecified As Boolean
        
        '<remarks/>
        Public ExternalAddressID As String
        
        '<remarks/>
        Public InternationalName As String
        
        '<remarks/>
        Public InternationalStateAndCity As String
        
        '<remarks/>
        Public InternationalStreet As String
        
        '<remarks/>
        Public AddressStatus As AddressStatusCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public AddressStatusSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum AddressOwnerCodeType
        
        '<remarks/>
        PayPal
        
        '<remarks/>
        eBay
        
        '<remarks/>
        CustomCode
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum AddressStatusCodeType
        
        '<remarks/>
        None
        
        '<remarks/>
        Confirmed
        
        '<remarks/>
        Unconfirmed
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class PaymentInfoType
        
        '<remarks/>
        Public TransactionID As String
        
        '<remarks/>
        Public ParentTransactionID As String
        
        '<remarks/>
        Public ReceiptID As String
        
        '<remarks/>
        Public TransactionType As PaymentTransactionCodeType
        
        '<remarks/>
        Public PaymentType As PaymentCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public PaymentTypeSpecified As Boolean
        
        '<remarks/>
        Public PaymentDate As Date
        
        '<remarks/>
        Public GrossAmount As BasicAmountType
        
        '<remarks/>
        Public FeeAmount As BasicAmountType
        
        '<remarks/>
        Public SettleAmount As BasicAmountType
        
        '<remarks/>
        Public TaxAmount As BasicAmountType
        
        '<remarks/>
        Public ExchangeRate As String
        
        '<remarks/>
        Public PaymentStatus As PaymentStatusCodeType
        
        '<remarks/>
        Public PendingReason As PendingStatusCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public PendingReasonSpecified As Boolean
        
        '<remarks/>
        Public ReasonCode As ReversalReasonCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ReasonCodeSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum PaymentTransactionCodeType
        
        '<remarks/>
        none
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("web-accept")>  _
        webaccept
        
        '<remarks/>
        cart
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("send-money")>  _
        sendmoney
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("subscr-failed")>  _
        subscrfailed
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("subscr-cancel")>  _
        subscrcancel
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("subscr-payment")>  _
        subscrpayment
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("subscr-signup")>  _
        subscrsignup
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("subscr-eot")>  _
        subscreot
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("subscr-modify")>  _
        subscrmodify
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("mercht-pmt")>  _
        merchtpmt
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("mass-pay")>  _
        masspay
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("virtual-terminal")>  _
        virtualterminal
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("express-checkout")>  _
        expresscheckout
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum PaymentCodeType
        
        '<remarks/>
        none
        
        '<remarks/>
        echeck
        
        '<remarks/>
        instant
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:CoreComponentTypes")>  _
    Public Class BasicAmountType
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public currencyID As CurrencyCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Value As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum CurrencyCodeType
        
        '<remarks/>
        AFA
        
        '<remarks/>
        ALL
        
        '<remarks/>
        DZD
        
        '<remarks/>
        ADP
        
        '<remarks/>
        AOA
        
        '<remarks/>
        ARS
        
        '<remarks/>
        AMD
        
        '<remarks/>
        AWG
        
        '<remarks/>
        AZM
        
        '<remarks/>
        BSD
        
        '<remarks/>
        BHD
        
        '<remarks/>
        BDT
        
        '<remarks/>
        BBD
        
        '<remarks/>
        BYR
        
        '<remarks/>
        BZD
        
        '<remarks/>
        BMD
        
        '<remarks/>
        BTN
        
        '<remarks/>
        INR
        
        '<remarks/>
        BOV
        
        '<remarks/>
        BOB
        
        '<remarks/>
        BAM
        
        '<remarks/>
        BWP
        
        '<remarks/>
        BRL
        
        '<remarks/>
        BND
        
        '<remarks/>
        BGL
        
        '<remarks/>
        BGN
        
        '<remarks/>
        BIF
        
        '<remarks/>
        KHR
        
        '<remarks/>
        CAD
        
        '<remarks/>
        CVE
        
        '<remarks/>
        KYD
        
        '<remarks/>
        XAF
        
        '<remarks/>
        CLF
        
        '<remarks/>
        CLP
        
        '<remarks/>
        CNY
        
        '<remarks/>
        COP
        
        '<remarks/>
        KMF
        
        '<remarks/>
        CDF
        
        '<remarks/>
        CRC
        
        '<remarks/>
        HRK
        
        '<remarks/>
        CUP
        
        '<remarks/>
        CYP
        
        '<remarks/>
        CZK
        
        '<remarks/>
        DKK
        
        '<remarks/>
        DJF
        
        '<remarks/>
        DOP
        
        '<remarks/>
        TPE
        
        '<remarks/>
        ECV
        
        '<remarks/>
        ECS
        
        '<remarks/>
        EGP
        
        '<remarks/>
        SVC
        
        '<remarks/>
        ERN
        
        '<remarks/>
        EEK
        
        '<remarks/>
        ETB
        
        '<remarks/>
        FKP
        
        '<remarks/>
        FJD
        
        '<remarks/>
        GMD
        
        '<remarks/>
        GEL
        
        '<remarks/>
        GHC
        
        '<remarks/>
        GIP
        
        '<remarks/>
        GTQ
        
        '<remarks/>
        GNF
        
        '<remarks/>
        GWP
        
        '<remarks/>
        GYD
        
        '<remarks/>
        HTG
        
        '<remarks/>
        HNL
        
        '<remarks/>
        HKD
        
        '<remarks/>
        HUF
        
        '<remarks/>
        ISK
        
        '<remarks/>
        IDR
        
        '<remarks/>
        IRR
        
        '<remarks/>
        IQD
        
        '<remarks/>
        ILS
        
        '<remarks/>
        JMD
        
        '<remarks/>
        JPY
        
        '<remarks/>
        JOD
        
        '<remarks/>
        KZT
        
        '<remarks/>
        KES
        
        '<remarks/>
        AUD
        
        '<remarks/>
        KPW
        
        '<remarks/>
        KRW
        
        '<remarks/>
        KWD
        
        '<remarks/>
        KGS
        
        '<remarks/>
        LAK
        
        '<remarks/>
        LVL
        
        '<remarks/>
        LBP
        
        '<remarks/>
        LSL
        
        '<remarks/>
        LRD
        
        '<remarks/>
        LYD
        
        '<remarks/>
        CHF
        
        '<remarks/>
        LTL
        
        '<remarks/>
        MOP
        
        '<remarks/>
        MKD
        
        '<remarks/>
        MGF
        
        '<remarks/>
        MWK
        
        '<remarks/>
        MYR
        
        '<remarks/>
        MVR
        
        '<remarks/>
        MTL
        
        '<remarks/>
        EUR
        
        '<remarks/>
        MRO
        
        '<remarks/>
        MUR
        
        '<remarks/>
        MXN
        
        '<remarks/>
        MXV
        
        '<remarks/>
        MDL
        
        '<remarks/>
        MNT
        
        '<remarks/>
        XCD
        
        '<remarks/>
        MZM
        
        '<remarks/>
        MMK
        
        '<remarks/>
        ZAR
        
        '<remarks/>
        NAD
        
        '<remarks/>
        NPR
        
        '<remarks/>
        ANG
        
        '<remarks/>
        XPF
        
        '<remarks/>
        NZD
        
        '<remarks/>
        NIO
        
        '<remarks/>
        NGN
        
        '<remarks/>
        NOK
        
        '<remarks/>
        OMR
        
        '<remarks/>
        PKR
        
        '<remarks/>
        PAB
        
        '<remarks/>
        PGK
        
        '<remarks/>
        PYG
        
        '<remarks/>
        PEN
        
        '<remarks/>
        PHP
        
        '<remarks/>
        PLN
        
        '<remarks/>
        USD
        
        '<remarks/>
        QAR
        
        '<remarks/>
        ROL
        
        '<remarks/>
        RUB
        
        '<remarks/>
        RUR
        
        '<remarks/>
        RWF
        
        '<remarks/>
        SHP
        
        '<remarks/>
        WST
        
        '<remarks/>
        STD
        
        '<remarks/>
        SAR
        
        '<remarks/>
        SCR
        
        '<remarks/>
        SLL
        
        '<remarks/>
        SGD
        
        '<remarks/>
        SKK
        
        '<remarks/>
        SIT
        
        '<remarks/>
        SBD
        
        '<remarks/>
        SOS
        
        '<remarks/>
        LKR
        
        '<remarks/>
        SDD
        
        '<remarks/>
        SRG
        
        '<remarks/>
        SZL
        
        '<remarks/>
        SEK
        
        '<remarks/>
        SYP
        
        '<remarks/>
        TWD
        
        '<remarks/>
        TJS
        
        '<remarks/>
        TZS
        
        '<remarks/>
        THB
        
        '<remarks/>
        XOF
        
        '<remarks/>
        TOP
        
        '<remarks/>
        TTD
        
        '<remarks/>
        TND
        
        '<remarks/>
        TRL
        
        '<remarks/>
        TMM
        
        '<remarks/>
        UGX
        
        '<remarks/>
        UAH
        
        '<remarks/>
        AED
        
        '<remarks/>
        GBP
        
        '<remarks/>
        USS
        
        '<remarks/>
        USN
        
        '<remarks/>
        UYU
        
        '<remarks/>
        UZS
        
        '<remarks/>
        VUV
        
        '<remarks/>
        VEB
        
        '<remarks/>
        VND
        
        '<remarks/>
        MAD
        
        '<remarks/>
        YER
        
        '<remarks/>
        YUM
        
        '<remarks/>
        ZMK
        
        '<remarks/>
        ZWD
        
        '<remarks/>
        CustomCode
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum PaymentStatusCodeType
        
        '<remarks/>
        None
        
        '<remarks/>
        Completed
        
        '<remarks/>
        Failed
        
        '<remarks/>
        Pending
        
        '<remarks/>
        Denied
        
        '<remarks/>
        Refunded
        
        '<remarks/>
        Reversed
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Canceled-Reversal")>  _
        CanceledReversal
        
        '<remarks/>
        Processed
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Partially-Refunded")>  _
        PartiallyRefunded
        
        '<remarks/>
        Voided
        
        '<remarks/>
        Expired
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("In-Progress")>  _
        InProgress
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum PendingStatusCodeType
        
        '<remarks/>
        none
        
        '<remarks/>
        echeck
        
        '<remarks/>
        intl
        
        '<remarks/>
        verify
        
        '<remarks/>
        address
        
        '<remarks/>
        unilateral
        
        '<remarks/>
        other
        
        '<remarks/>
        upgrade
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("multi-currency")>  _
        multicurrency
        
        '<remarks/>
        authorization
        
        '<remarks/>
        order
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum ReversalReasonCodeType
        
        '<remarks/>
        none
        
        '<remarks/>
        chargeback
        
        '<remarks/>
        guarantee
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("buyer-complaint")>  _
        buyercomplaint
        
        '<remarks/>
        refund
        
        '<remarks/>
        other
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class MerchantPullInfoType
        
        '<remarks/>
        Public MpStatus As MerchantPullStatusCodeType
        
        '<remarks/>
        Public MpMax As BasicAmountType
        
        '<remarks/>
        Public MpCustom As String
        
        '<remarks/>
        Public Desc As String
        
        '<remarks/>
        Public Invoice As String
        
        '<remarks/>
        Public Custom As String
        
        '<remarks/>
        Public PaymentSourceID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum MerchantPullStatusCodeType
        
        '<remarks/>
        Active
        
        '<remarks/>
        Canceled
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class BAUpdateResponseDetailsType
        
        '<remarks/>
        Public MpID As String
        
        '<remarks/>
        Public PayerInfo As PayerInfoType
        
        '<remarks/>
        Public MerchantPullInfo As MerchantPullInfoType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class GetExpressCheckoutDetailsResponseDetailsType
        
        '<remarks/>
        Public Token As String
        
        '<remarks/>
        Public PayerInfo As PayerInfoType
        
        '<remarks/>
        Public Custom As String
        
        '<remarks/>
        Public InvoiceID As String
        
        '<remarks/>
        Public ContactPhone As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class DoExpressCheckoutPaymentResponseDetailsType
        
        '<remarks/>
        Public Token As String
        
        '<remarks/>
        Public PaymentInfo As PaymentInfoType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class PaymentTransactionSearchResultType
        
        '<remarks/>
        Public Timestamp As Date
        
        '<remarks/>
        Public Timezone As String
        
        '<remarks/>
        Public Type As String
        
        '<remarks/>
        Public Payer As String
        
        '<remarks/>
        Public PayerDisplayName As String
        
        '<remarks/>
        Public TransactionID As String
        
        '<remarks/>
        Public Status As String
        
        '<remarks/>
        Public GrossAmount As BasicAmountType
        
        '<remarks/>
        Public FeeAmount As BasicAmountType
        
        '<remarks/>
        Public NetAmount As BasicAmountType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class AuctionInfoType
        
        '<remarks/>
        Public BuyerID As String
        
        '<remarks/>
        Public ClosingDate As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ClosingDateSpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public multiItem As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class SubscriptionTermsType
        
        '<remarks/>
        Public Amount As BasicAmountType
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public period As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class SubscriptionInfoType
        
        '<remarks/>
        Public SubscriptionID As String
        
        '<remarks/>
        Public SubscriptionDate As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public SubscriptionDateSpecified As Boolean
        
        '<remarks/>
        Public EffectiveDate As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public EffectiveDateSpecified As Boolean
        
        '<remarks/>
        Public RetryTime As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public RetryTimeSpecified As Boolean
        
        '<remarks/>
        Public Username As String
        
        '<remarks/>
        Public Password As String
        
        '<remarks/>
        Public Recurrences As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Terms")>  _
        Public Terms() As SubscriptionTermsType
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public reattempt As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public recurring As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class OptionType
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public name As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public value As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class PaymentItemType
        
        '<remarks/>
        Public Name As String
        
        '<remarks/>
        Public Number As String
        
        '<remarks/>
        Public Quantity As String
        
        '<remarks/>
        Public SalesTax As String
        
        '<remarks/>
        Public Amount As BasicAmountType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Options")>  _
        Public Options() As OptionType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class PaymentItemInfoType
        
        '<remarks/>
        Public InvoiceID As String
        
        '<remarks/>
        Public Custom As String
        
        '<remarks/>
        Public Memo As String
        
        '<remarks/>
        Public SalesTax As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PaymentItem")>  _
        Public PaymentItem() As PaymentItemType
        
        '<remarks/>
        Public Subscription As SubscriptionInfoType
        
        '<remarks/>
        Public Auction As AuctionInfoType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class ReceiverInfoType
        
        '<remarks/>
        Public Business As String
        
        '<remarks/>
        Public Receiver As String
        
        '<remarks/>
        Public ReceiverID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class PaymentTransactionType
        
        '<remarks/>
        Public ReceiverInfo As ReceiverInfoType
        
        '<remarks/>
        Public PayerInfo As PayerInfoType
        
        '<remarks/>
        Public PaymentInfo As PaymentInfoType
        
        '<remarks/>
        Public PaymentItemInfo As PaymentItemInfoType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class DoCaptureResponseDetailsType
        
        '<remarks/>
        Public AuthorizationID As String
        
        '<remarks/>
        Public PaymentInfo As PaymentInfoType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class APICredentialsType
        
        '<remarks/>
        Public Username As String
        
        '<remarks/>
        Public Password As String
        
        '<remarks/>
        Public Signature As String
        
        '<remarks/>
        Public Certificate As String
        
        '<remarks/>
        Public Type As APIAuthenticationType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum APIAuthenticationType
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Auth-None")>  _
        AuthNone
        
        '<remarks/>
        Cert
        
        '<remarks/>
        Sign
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Class GetBoardingDetailsResponseDetailsType
        
        '<remarks/>
        Public Status As BoardingStatusType
        
        '<remarks/>
        Public StartDate As Date
        
        '<remarks/>
        Public LastUpdated As Date
        
        '<remarks/>
        Public Reason As String
        
        '<remarks/>
        Public ProgramName As String
        
        '<remarks/>
        Public ProgramCode As String
        
        '<remarks/>
        Public CampaignID As String
        
        '<remarks/>
        Public UserWithdrawalLimit As UserWithdrawalLimitTypeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public UserWithdrawalLimitSpecified As Boolean
        
        '<remarks/>
        Public PartnerCustom As String
        
        '<remarks/>
        Public AccountOwner As PayerInfoType
        
        '<remarks/>
        Public Credentials As APICredentialsType
        
        '<remarks/>
        Public ConfigureAPIs As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum BoardingStatusType
        
        '<remarks/>
        Unknown
        
        '<remarks/>
        Completed
        
        '<remarks/>
        Cancelled
        
        '<remarks/>
        Pending
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum UserWithdrawalLimitTypeType
        
        '<remarks/>
        Unknown
        
        '<remarks/>
        Limited
        
        '<remarks/>
        Unlimited
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class MassPayResponseType
        Inherits AbstractResponseType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class DoDirectPaymentResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        Public Amount As BasicAmountType
        
        '<remarks/>
        Public AVSCode As String
        
        '<remarks/>
        Public CVV2Code As String
        
        '<remarks/>
        Public TransactionID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class BillUserResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public BillUserResponseDetails As MerchantPullPaymentResponseType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class BAUpdateResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public BAUpdateResponseDetails As BAUpdateResponseDetailsType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class DoAuthorizationResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        Public TransactionID As String
        
        '<remarks/>
        Public Amount As BasicAmountType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class GetExpressCheckoutDetailsResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public GetExpressCheckoutDetailsResponseDetails As GetExpressCheckoutDetailsResponseDetailsType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class DoExpressCheckoutPaymentResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public DoExpressCheckoutPaymentResponseDetails As DoExpressCheckoutPaymentResponseDetailsType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class TransactionSearchResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PaymentTransactions", [Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public PaymentTransactions() As PaymentTransactionSearchResultType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class RefundTransactionResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public RefundTransactionID As String
        
        '<remarks/>
        Public NetRefundAmount As BasicAmountType
        
        '<remarks/>
        Public FeeRefundAmount As BasicAmountType
        
        '<remarks/>
        Public GrossRefundAmount As BasicAmountType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class GetTransactionDetailsResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public PaymentTransactionDetails As PaymentTransactionType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class EnterBoardingResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        Public Token As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class AddressVerifyResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        Public ConfirmationCode As AddressStatusCodeType
        
        '<remarks/>
        Public StreetMatch As MatchStatusCodeType
        
        '<remarks/>
        Public ZipMatch As MatchStatusCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ZipMatchSpecified As Boolean
        
        '<remarks/>
        Public CountryCode As CountryCodeType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public CountryCodeSpecified As Boolean
        
        '<remarks/>
        Public PayPalToken As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum MatchStatusCodeType
        
        '<remarks/>
        None
        
        '<remarks/>
        Matched
        
        '<remarks/>
        Unmatched
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class DoCaptureResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public DoCaptureResponseDetails As DoCaptureResponseDetailsType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class GetMobileStatusResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public IsActivated As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public PaymentPending As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class DoReauthorizationResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        Public AuthorizationID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class DoVoidResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        Public AuthorizationID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class CreateMobilePaymentResponseType
        Inherits AbstractResponseType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:api:PayPalAPI")>  _
    Public Class GetBoardingDetailsResponseType
        Inherits AbstractResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
        Public GetBoardingDetailsResponseDetails As GetBoardingDetailsResponseDetailsType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:ebay:apis:eBLBaseComponents")>  _
    Public Enum PaymentActionCodeType
        
        '<remarks/>
        None
        
        '<remarks/>
        Authorization
        
        '<remarks/>
        Sale
        
        '<remarks/>
        Order
    End Enum
End Namespace
