'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace com.webservices.ishops
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="OrderProcessingSoap", [Namespace]:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing")>  _
    Public Class OrderProcessing
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("WindowsGateWayCreditCard.com.webservices.ishops.OrderProcessing")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://ishops.webservices.com/order/orderprocessing.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Infinishops.Support.Web/OrderProcessing/ProcessOrder", RequestNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", ResponseNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessOrder(ByVal dsOrderInformation As System.Data.DataSet) As Integer
            Dim results() As Object = Me.Invoke("ProcessOrder", New Object() {dsOrderInformation})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginProcessOrder(ByVal dsOrderInformation As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ProcessOrder", New Object() {dsOrderInformation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndProcessOrder(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Infinishops.Support.Web/OrderProcessing/ProcessOrderXml", RequestNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", ResponseNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessOrderXml(ByVal OrderInformationXml As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessOrderXml", New Object() {OrderInformationXml})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginProcessOrderXml(ByVal OrderInformationXml As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ProcessOrderXml", New Object() {OrderInformationXml}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndProcessOrderXml(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Infinishops.Support.Web/OrderProcessing/Test", RequestNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", ResponseNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Test(ByVal TestData As String) As String
            Dim results() As Object = Me.Invoke("Test", New Object() {TestData})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginTest(ByVal TestData As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Test", New Object() {TestData}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTest(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Infinishops.Support.Web/OrderProcessing/GenerateInvoiceForOrde"& _ 
"r", RequestNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", ResponseNamespace:="http://tempuri.org/Infinishops.Support.Web/OrderProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenerateInvoiceForOrder(ByVal OrderInformationXML As String) As String
            Dim results() As Object = Me.Invoke("GenerateInvoiceForOrder", New Object() {OrderInformationXML})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGenerateInvoiceForOrder(ByVal OrderInformationXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GenerateInvoiceForOrder", New Object() {OrderInformationXML}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGenerateInvoiceForOrder(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
