'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace ServiceActivation
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceActivationSoap", [Namespace]:="http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation")>  _
    Public Class ServiceActivation
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://cxlrobot.accountscentre.com/CXLRobot_ServiceActivation/ServiceActivation.a"& _ 
"smx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation/EnabledServices", RequestNamespace:="http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation", ResponseNamespace:="http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnabledServices(ByVal CustomerID As Integer, ByVal OrderID As Integer, ByVal IsOrderSuccess As Boolean, ByVal PayMode As String) As Object
            Dim results() As Object = Me.Invoke("EnabledServices", New Object() {CustomerID, OrderID, IsOrderSuccess, PayMode})
            Return CType(results(0),Object)
        End Function
        
        '<remarks/>
        Public Function BeginEnabledServices(ByVal CustomerID As Integer, ByVal OrderID As Integer, ByVal IsOrderSuccess As Boolean, ByVal PayMode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EnabledServices", New Object() {CustomerID, OrderID, IsOrderSuccess, PayMode}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEnabledServices(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation/GetBizInfo", RequestNamespace:="http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation", ResponseNamespace:="http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBizInfo(ByVal ResellerUID As Integer, ByVal OrderID As Integer, ByVal CustomerID As Integer, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal Product() As ProductDetail, ByVal PayStatus As String) As GetBizInfoResult
            Dim results() As Object = Me.Invoke("GetBizInfo", New Object() {ResellerUID, OrderID, CustomerID, Product, PayStatus})
            Return CType(results(0),GetBizInfoResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetBizInfo(ByVal ResellerUID As Integer, ByVal OrderID As Integer, ByVal CustomerID As Integer, ByVal Product() As ProductDetail, ByVal PayStatus As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetBizInfo", New Object() {ResellerUID, OrderID, CustomerID, Product, PayStatus}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetBizInfo(ByVal asyncResult As System.IAsyncResult) As GetBizInfoResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetBizInfoResult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation")>  _
    Public Class GetBizInfoResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CXLRobot_ServiceActivation/ServiceActivation")>  _
    Public Class ProductDetail
        
        '<remarks/>
        Public ProductCode As String
        
        '<remarks/>
        Public Quantity As String
    End Class
End Namespace
