'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
'
Namespace com.accountscentre.callback
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CallBackServiceSoap", [Namespace]:="http://callback.accountscentre.com/")>  _
    Public Class CallBackService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://callback.accountscentre.com/services/CallBackService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://callback.accountscentre.com/PostCallBackData", RequestNamespace:="http://callback.accountscentre.com/", ResponseNamespace:="http://callback.accountscentre.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PostCallBackData(ByVal MIdentity As String, ByVal OrderID As String, ByVal GenericCode As String, ByVal Amount As String, ByVal TrackID As String, ByVal IsOrderSuccess As Boolean, ByVal IsOrderByBank As Boolean) As ServiceResponse
            Dim results() As Object = Me.Invoke("PostCallBackData", New Object() {MIdentity, OrderID, GenericCode, Amount, TrackID, IsOrderSuccess, IsOrderByBank})
            Return CType(results(0),ServiceResponse)
        End Function
        
        '<remarks/>
        Public Function BeginPostCallBackData(ByVal MIdentity As String, ByVal OrderID As String, ByVal GenericCode As String, ByVal Amount As String, ByVal TrackID As String, ByVal IsOrderSuccess As Boolean, ByVal IsOrderByBank As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PostCallBackData", New Object() {MIdentity, OrderID, GenericCode, Amount, TrackID, IsOrderSuccess, IsOrderByBank}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndPostCallBackData(ByVal asyncResult As System.IAsyncResult) As ServiceResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ServiceResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://callback.accountscentre.com/")>  _
    Public Class ServiceResponse
        
        '<remarks/>
        Public ErrorCode As Short
        
        '<remarks/>
        Public ErrorMsg As String
    End Class
End Namespace
