'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace com.infinishops.addSupplier
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AddSupplierSoap", [Namespace]:="http://tempuri.org/couponsystem.infinishops.com/AddSupplier")>  _
    Public Class AddSupplier
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://couponsystem.infinishops.com/AddSupplier.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/couponsystem.infinishops.com/AddSupplier/AddSupplier", RequestNamespace:="http://tempuri.org/couponsystem.infinishops.com/AddSupplier", ResponseNamespace:="http://tempuri.org/couponsystem.infinishops.com/AddSupplier", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddSupplier(ByVal MerchantID As Integer, ByVal CustomerID As Integer, ByVal OrderId As Integer) As ErrorCodesInfo
            Dim results() As Object = Me.Invoke("AddSupplier", New Object() {MerchantID, CustomerID, OrderId})
            Return CType(results(0),ErrorCodesInfo)
        End Function
        
        '<remarks/>
        Public Function BeginAddSupplier(ByVal MerchantID As Integer, ByVal CustomerID As Integer, ByVal OrderId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddSupplier", New Object() {MerchantID, CustomerID, OrderId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddSupplier(ByVal asyncResult As System.IAsyncResult) As ErrorCodesInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorCodesInfo)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/couponsystem.infinishops.com/AddSupplier")>  _
    Public Class ErrorCodesInfo
        
        '<remarks/>
        Public ErrorCode As Integer
        
        '<remarks/>
        Public ErrorDescription As String
    End Class
End Namespace
