'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
'
Namespace InvoicePostWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AccountsProServiceSoap", [Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class AccountsProService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreateAccountsProUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateEmployeeIOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RefundRobot_PostCreditInvoiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CXLRobot_PostInvoiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateSupplierFromCustomerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateNewSubscriptionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreatePaidOrderSubscriptionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://accountsws.accountscentre.com/AccountsProService.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateAccountsProUserCompleted As CreateAccountsProUserCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateEmployeeIOCompleted As CreateEmployeeIOCompletedEventHandler
        
        '''<remarks/>
        Public Event RefundRobot_PostCreditInvoiceCompleted As RefundRobot_PostCreditInvoiceCompletedEventHandler
        
        '''<remarks/>
        Public Event CXLRobot_PostInvoiceCompleted As CXLRobot_PostInvoiceCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateSupplierFromCustomerCompleted As CreateSupplierFromCustomerCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateNewSubscriptionCompleted As CreateNewSubscriptionCompletedEventHandler
        
        '''<remarks/>
        Public Event CreatePaidOrderSubscriptionCompleted As CreatePaidOrderSubscriptionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsProWS/Service1/CreateAccountsProUser", RequestNamespace:="http://tempuri.org/AccountsProWS/Service1", ResponseNamespace:="http://tempuri.org/AccountsProWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateAccountsProUser(ByVal UserInfoStruct As AccountsProUserInfoToCreate) As TransactionReport
            Dim results() As Object = Me.Invoke("CreateAccountsProUser", New Object() {UserInfoStruct})
            Return CType(results(0),TransactionReport)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateAccountsProUser(ByVal UserInfoStruct As AccountsProUserInfoToCreate, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateAccountsProUser", New Object() {UserInfoStruct}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateAccountsProUser(ByVal asyncResult As System.IAsyncResult) As TransactionReport
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TransactionReport)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateAccountsProUserAsync(ByVal UserInfoStruct As AccountsProUserInfoToCreate)
            Me.CreateAccountsProUserAsync(UserInfoStruct, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAccountsProUserAsync(ByVal UserInfoStruct As AccountsProUserInfoToCreate, ByVal userState As Object)
            If (Me.CreateAccountsProUserOperationCompleted Is Nothing) Then
                Me.CreateAccountsProUserOperationCompleted = AddressOf Me.OnCreateAccountsProUserOperationCompleted
            End If
            Me.InvokeAsync("CreateAccountsProUser", New Object() {UserInfoStruct}, Me.CreateAccountsProUserOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateAccountsProUserOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateAccountsProUserCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateAccountsProUserCompleted(Me, New CreateAccountsProUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsProWS/Service1/CreateEmployeeIO", RequestNamespace:="http://tempuri.org/AccountsProWS/Service1", ResponseNamespace:="http://tempuri.org/AccountsProWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateEmployeeIO(ByVal UserInfoStruct As EmployeeInfoToCreate) As EmployeeTransactionReport
            Dim results() As Object = Me.Invoke("CreateEmployeeIO", New Object() {UserInfoStruct})
            Return CType(results(0),EmployeeTransactionReport)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateEmployeeIO(ByVal UserInfoStruct As EmployeeInfoToCreate, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateEmployeeIO", New Object() {UserInfoStruct}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateEmployeeIO(ByVal asyncResult As System.IAsyncResult) As EmployeeTransactionReport
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EmployeeTransactionReport)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateEmployeeIOAsync(ByVal UserInfoStruct As EmployeeInfoToCreate)
            Me.CreateEmployeeIOAsync(UserInfoStruct, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateEmployeeIOAsync(ByVal UserInfoStruct As EmployeeInfoToCreate, ByVal userState As Object)
            If (Me.CreateEmployeeIOOperationCompleted Is Nothing) Then
                Me.CreateEmployeeIOOperationCompleted = AddressOf Me.OnCreateEmployeeIOOperationCompleted
            End If
            Me.InvokeAsync("CreateEmployeeIO", New Object() {UserInfoStruct}, Me.CreateEmployeeIOOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateEmployeeIOOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateEmployeeIOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateEmployeeIOCompleted(Me, New CreateEmployeeIOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsProWS/Service1/RefundRobot_PostCreditInvoice", RequestNamespace:="http://tempuri.org/AccountsProWS/Service1", ResponseNamespace:="http://tempuri.org/AccountsProWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RefundRobot_PostCreditInvoice(ByVal MerchantID As Integer, ByVal CreditInvoiceNo As Integer) As String
            Dim results() As Object = Me.Invoke("RefundRobot_PostCreditInvoice", New Object() {MerchantID, CreditInvoiceNo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginRefundRobot_PostCreditInvoice(ByVal MerchantID As Integer, ByVal CreditInvoiceNo As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RefundRobot_PostCreditInvoice", New Object() {MerchantID, CreditInvoiceNo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRefundRobot_PostCreditInvoice(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RefundRobot_PostCreditInvoiceAsync(ByVal MerchantID As Integer, ByVal CreditInvoiceNo As Integer)
            Me.RefundRobot_PostCreditInvoiceAsync(MerchantID, CreditInvoiceNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RefundRobot_PostCreditInvoiceAsync(ByVal MerchantID As Integer, ByVal CreditInvoiceNo As Integer, ByVal userState As Object)
            If (Me.RefundRobot_PostCreditInvoiceOperationCompleted Is Nothing) Then
                Me.RefundRobot_PostCreditInvoiceOperationCompleted = AddressOf Me.OnRefundRobot_PostCreditInvoiceOperationCompleted
            End If
            Me.InvokeAsync("RefundRobot_PostCreditInvoice", New Object() {MerchantID, CreditInvoiceNo}, Me.RefundRobot_PostCreditInvoiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnRefundRobot_PostCreditInvoiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.RefundRobot_PostCreditInvoiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RefundRobot_PostCreditInvoiceCompleted(Me, New RefundRobot_PostCreditInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsProWS/Service1/CXLRobot_PostInvoice", RequestNamespace:="http://tempuri.org/AccountsProWS/Service1", ResponseNamespace:="http://tempuri.org/AccountsProWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CXLRobot_PostInvoice(ByVal MerchantID As Integer, ByVal InvoiceNo As Integer) As String
            Dim results() As Object = Me.Invoke("CXLRobot_PostInvoice", New Object() {MerchantID, InvoiceNo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCXLRobot_PostInvoice(ByVal MerchantID As Integer, ByVal InvoiceNo As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CXLRobot_PostInvoice", New Object() {MerchantID, InvoiceNo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCXLRobot_PostInvoice(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CXLRobot_PostInvoiceAsync(ByVal MerchantID As Integer, ByVal InvoiceNo As Integer)
            Me.CXLRobot_PostInvoiceAsync(MerchantID, InvoiceNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CXLRobot_PostInvoiceAsync(ByVal MerchantID As Integer, ByVal InvoiceNo As Integer, ByVal userState As Object)
            If (Me.CXLRobot_PostInvoiceOperationCompleted Is Nothing) Then
                Me.CXLRobot_PostInvoiceOperationCompleted = AddressOf Me.OnCXLRobot_PostInvoiceOperationCompleted
            End If
            Me.InvokeAsync("CXLRobot_PostInvoice", New Object() {MerchantID, InvoiceNo}, Me.CXLRobot_PostInvoiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnCXLRobot_PostInvoiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.CXLRobot_PostInvoiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CXLRobot_PostInvoiceCompleted(Me, New CXLRobot_PostInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsProWS/Service1/CreateSupplierFromCustomer", RequestNamespace:="http://tempuri.org/AccountsProWS/Service1", ResponseNamespace:="http://tempuri.org/AccountsProWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateSupplierFromCustomer(ByVal SupplierData As SupplierInfo) As SupplierFromCustomerResponse
            Dim results() As Object = Me.Invoke("CreateSupplierFromCustomer", New Object() {SupplierData})
            Return CType(results(0),SupplierFromCustomerResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateSupplierFromCustomer(ByVal SupplierData As SupplierInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateSupplierFromCustomer", New Object() {SupplierData}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateSupplierFromCustomer(ByVal asyncResult As System.IAsyncResult) As SupplierFromCustomerResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SupplierFromCustomerResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateSupplierFromCustomerAsync(ByVal SupplierData As SupplierInfo)
            Me.CreateSupplierFromCustomerAsync(SupplierData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateSupplierFromCustomerAsync(ByVal SupplierData As SupplierInfo, ByVal userState As Object)
            If (Me.CreateSupplierFromCustomerOperationCompleted Is Nothing) Then
                Me.CreateSupplierFromCustomerOperationCompleted = AddressOf Me.OnCreateSupplierFromCustomerOperationCompleted
            End If
            Me.InvokeAsync("CreateSupplierFromCustomer", New Object() {SupplierData}, Me.CreateSupplierFromCustomerOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateSupplierFromCustomerOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateSupplierFromCustomerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateSupplierFromCustomerCompleted(Me, New CreateSupplierFromCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsProWS/Service1/CreateNewSubscription", RequestNamespace:="http://tempuri.org/AccountsProWS/Service1", ResponseNamespace:="http://tempuri.org/AccountsProWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateNewSubscription(ByVal MerchantID As Integer, ByVal OrderID As Integer) As SubscriptionResponse
            Dim results() As Object = Me.Invoke("CreateNewSubscription", New Object() {MerchantID, OrderID})
            Return CType(results(0),SubscriptionResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateNewSubscription(ByVal MerchantID As Integer, ByVal OrderID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateNewSubscription", New Object() {MerchantID, OrderID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateNewSubscription(ByVal asyncResult As System.IAsyncResult) As SubscriptionResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SubscriptionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateNewSubscriptionAsync(ByVal MerchantID As Integer, ByVal OrderID As Integer)
            Me.CreateNewSubscriptionAsync(MerchantID, OrderID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateNewSubscriptionAsync(ByVal MerchantID As Integer, ByVal OrderID As Integer, ByVal userState As Object)
            If (Me.CreateNewSubscriptionOperationCompleted Is Nothing) Then
                Me.CreateNewSubscriptionOperationCompleted = AddressOf Me.OnCreateNewSubscriptionOperationCompleted
            End If
            Me.InvokeAsync("CreateNewSubscription", New Object() {MerchantID, OrderID}, Me.CreateNewSubscriptionOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateNewSubscriptionOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateNewSubscriptionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateNewSubscriptionCompleted(Me, New CreateNewSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsProWS/Service1/CreatePaidOrderSubscription", RequestNamespace:="http://tempuri.org/AccountsProWS/Service1", ResponseNamespace:="http://tempuri.org/AccountsProWS/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreatePaidOrderSubscription(ByVal MerchantID As Integer, ByVal OrderID As Integer, ByVal ProductCode As String, ByVal Qty As Double, ByVal SubsInterval As Integer) As SubscriptionResponse
            Dim results() As Object = Me.Invoke("CreatePaidOrderSubscription", New Object() {MerchantID, OrderID, ProductCode, Qty, SubsInterval})
            Return CType(results(0),SubscriptionResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginCreatePaidOrderSubscription(ByVal MerchantID As Integer, ByVal OrderID As Integer, ByVal ProductCode As String, ByVal Qty As Double, ByVal SubsInterval As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreatePaidOrderSubscription", New Object() {MerchantID, OrderID, ProductCode, Qty, SubsInterval}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreatePaidOrderSubscription(ByVal asyncResult As System.IAsyncResult) As SubscriptionResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SubscriptionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreatePaidOrderSubscriptionAsync(ByVal MerchantID As Integer, ByVal OrderID As Integer, ByVal ProductCode As String, ByVal Qty As Double, ByVal SubsInterval As Integer)
            Me.CreatePaidOrderSubscriptionAsync(MerchantID, OrderID, ProductCode, Qty, SubsInterval, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreatePaidOrderSubscriptionAsync(ByVal MerchantID As Integer, ByVal OrderID As Integer, ByVal ProductCode As String, ByVal Qty As Double, ByVal SubsInterval As Integer, ByVal userState As Object)
            If (Me.CreatePaidOrderSubscriptionOperationCompleted Is Nothing) Then
                Me.CreatePaidOrderSubscriptionOperationCompleted = AddressOf Me.OnCreatePaidOrderSubscriptionOperationCompleted
            End If
            Me.InvokeAsync("CreatePaidOrderSubscription", New Object() {MerchantID, OrderID, ProductCode, Qty, SubsInterval}, Me.CreatePaidOrderSubscriptionOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreatePaidOrderSubscriptionOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreatePaidOrderSubscriptionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreatePaidOrderSubscriptionCompleted(Me, New CreatePaidOrderSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class AccountsProUserInfoToCreate
        
        Private customerIdField As Integer
        
        Private userNameField As String
        
        Private userPasswordField As String
        
        Private userEmailField As String
        
        '''<remarks/>
        Public Property CustomerId() As Integer
            Get
                Return Me.customerIdField
            End Get
            Set
                Me.customerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserPassword() As String
            Get
                Return Me.userPasswordField
            End Get
            Set
                Me.userPasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserEmail() As String
            Get
                Return Me.userEmailField
            End Get
            Set
                Me.userEmailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class SubscriptionResponse
        
        Private errorCodeField As Integer
        
        Private errorDescriptionField As String
        
        Private moreErrorDescriptionField As String
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MoreErrorDescription() As String
            Get
                Return Me.moreErrorDescriptionField
            End Get
            Set
                Me.moreErrorDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class SupplierFromCustomerResponse
        
        Private supplierIDField As Integer
        
        Private errorCodeField As Integer
        
        Private errorDescriptionField As String
        
        Private moreErrorDescriptionField As String
        
        '''<remarks/>
        Public Property SupplierID() As Integer
            Get
                Return Me.supplierIDField
            End Get
            Set
                Me.supplierIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MoreErrorDescription() As String
            Get
                Return Me.moreErrorDescriptionField
            End Get
            Set
                Me.moreErrorDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class SupplierInfo
        
        Private merchantIDField As Integer
        
        Private custIDField As Integer
        
        Private supplierNameField As String
        
        Private streetField As String
        
        Private cityField As String
        
        Private postalCodeField As String
        
        Private countryField As String
        
        Private telephoneField As String
        
        Private faxField As String
        
        Private contactNameField As String
        
        Private emailField As String
        
        '''<remarks/>
        Public Property MerchantID() As Integer
            Get
                Return Me.merchantIDField
            End Get
            Set
                Me.merchantIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustID() As Integer
            Get
                Return Me.custIDField
            End Get
            Set
                Me.custIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SupplierName() As String
            Get
                Return Me.supplierNameField
            End Get
            Set
                Me.supplierNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Street() As String
            Get
                Return Me.streetField
            End Get
            Set
                Me.streetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Telephone() As String
            Get
                Return Me.telephoneField
            End Get
            Set
                Me.telephoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactName() As String
            Get
                Return Me.contactNameField
            End Get
            Set
                Me.contactNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class EmployeeTransactionReport
        
        Private employeeIDField As String
        
        Private errorCodeField As Integer
        
        Private errorDescriptionField As String
        
        Private moreErrorDescriptionField As String
        
        '''<remarks/>
        Public Property EmployeeID() As String
            Get
                Return Me.employeeIDField
            End Get
            Set
                Me.employeeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MoreErrorDescription() As String
            Get
                Return Me.moreErrorDescriptionField
            End Get
            Set
                Me.moreErrorDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class EmployeeInfoToCreate
        
        Private merchantIdField As Integer
        
        Private customerIdField As Integer
        
        '''<remarks/>
        Public Property MerchantId() As Integer
            Get
                Return Me.merchantIdField
            End Get
            Set
                Me.merchantIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerId() As Integer
            Get
                Return Me.customerIdField
            End Get
            Set
                Me.customerIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AccountsProWS/Service1")>  _
    Partial Public Class TransactionReport
        
        Private errorCodeField As Integer
        
        Private errorDescriptionField As String
        
        Private moreErrorDescriptionField As String
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MoreErrorDescription() As String
            Get
                Return Me.moreErrorDescriptionField
            End Get
            Set
                Me.moreErrorDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CreateAccountsProUserCompletedEventHandler(ByVal sender As Object, ByVal e As CreateAccountsProUserCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateAccountsProUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TransactionReport
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TransactionReport)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CreateEmployeeIOCompletedEventHandler(ByVal sender As Object, ByVal e As CreateEmployeeIOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateEmployeeIOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EmployeeTransactionReport
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EmployeeTransactionReport)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub RefundRobot_PostCreditInvoiceCompletedEventHandler(ByVal sender As Object, ByVal e As RefundRobot_PostCreditInvoiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RefundRobot_PostCreditInvoiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CXLRobot_PostInvoiceCompletedEventHandler(ByVal sender As Object, ByVal e As CXLRobot_PostInvoiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CXLRobot_PostInvoiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CreateSupplierFromCustomerCompletedEventHandler(ByVal sender As Object, ByVal e As CreateSupplierFromCustomerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateSupplierFromCustomerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SupplierFromCustomerResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SupplierFromCustomerResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CreateNewSubscriptionCompletedEventHandler(ByVal sender As Object, ByVal e As CreateNewSubscriptionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateNewSubscriptionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SubscriptionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SubscriptionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CreatePaidOrderSubscriptionCompletedEventHandler(ByVal sender As Object, ByVal e As CreatePaidOrderSubscriptionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreatePaidOrderSubscriptionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SubscriptionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SubscriptionResponse)
            End Get
        End Property
    End Class
End Namespace
