'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace Io.InfiniShops
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceActivationSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class ServiceActivation
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://io.infinishops.com/services/ServiceActivation.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnabledServices", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnabledServices(ByVal info As ServiceInfo) As EnabledServicesResult
            Dim results() As Object = Me.Invoke("EnabledServices", New Object() {info})
            Return CType(results(0),EnabledServicesResult)
        End Function
        
        '<remarks/>
        Public Function BeginEnabledServices(ByVal info As ServiceInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EnabledServices", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEnabledServices(ByVal asyncResult As System.IAsyncResult) As EnabledServicesResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EnabledServicesResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTicketText", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTicketText(ByVal info As Ticket_Info) As GetTicketTextResult
            Dim results() As Object = Me.Invoke("GetTicketText", New Object() {info})
            Return CType(results(0),GetTicketTextResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetTicketText(ByVal info As Ticket_Info, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTicketText", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTicketText(ByVal asyncResult As System.IAsyncResult) As GetTicketTextResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetTicketTextResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTicketTextByTicketCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTicketTextByTicketCode(ByVal info As TicketCodeParams) As GetTicketTextResult
            Dim results() As Object = Me.Invoke("GetTicketTextByTicketCode", New Object() {info})
            Return CType(results(0),GetTicketTextResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetTicketTextByTicketCode(ByVal info As TicketCodeParams, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTicketTextByTicketCode", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTicketTextByTicketCode(ByVal asyncResult As System.IAsyncResult) As GetTicketTextResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetTicketTextResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TicketHandler", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TicketHandler(ByVal info As TicketHandlerInfo) As TicketHandlerResult
            Dim results() As Object = Me.Invoke("TicketHandler", New Object() {info})
            Return CType(results(0),TicketHandlerResult)
        End Function
        
        '<remarks/>
        Public Function BeginTicketHandler(ByVal info As TicketHandlerInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TicketHandler", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTicketHandler(ByVal asyncResult As System.IAsyncResult) As TicketHandlerResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TicketHandlerResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RepayTicketHandler_PayOnCredit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RepayTicketHandler_PayOnCredit(ByVal info As ServiceInfo) As TicketHandlerResult
            Dim results() As Object = Me.Invoke("RepayTicketHandler_PayOnCredit", New Object() {info})
            Return CType(results(0),TicketHandlerResult)
        End Function
        
        '<remarks/>
        Public Function BeginRepayTicketHandler_PayOnCredit(ByVal info As ServiceInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RepayTicketHandler_PayOnCredit", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRepayTicketHandler_PayOnCredit(ByVal asyncResult As System.IAsyncResult) As TicketHandlerResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TicketHandlerResult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class ServiceInfo
        
        '<remarks/>
        Public MerchantID As String
        
        '<remarks/>
        Public CustomerID As String
        
        '<remarks/>
        Public OrderID As String
        
        '<remarks/>
        Public IsOrderSuccess As Boolean
        
        '<remarks/>
        Public PayMode As PaymentMode
        
        '<remarks/>
        Public DotNotSendDeclineEmail As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum PaymentMode
        
        '<remarks/>
        CC
        
        '<remarks/>
        CB
        
        '<remarks/>
        BP
        
        '<remarks/>
        PA
        
        '<remarks/>
        CR
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class TicketHandlerResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class TicketHandlerInfo
        
        '<remarks/>
        Public MerchantID As String
        
        '<remarks/>
        Public CustomerID As String
        
        '<remarks/>
        Public OrderID As String
        
        '<remarks/>
        Public PayMode As PaymentMode
        
        '<remarks/>
        Public IsRepayment As Boolean
        
        '<remarks/>
        Public OrderAmount As Double
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class TicketCodeParams
        
        '<remarks/>
        Public MerchantID As String
        
        '<remarks/>
        Public TicketCode As String
        
        '<remarks/>
        Public AttributeName As String
        
        '<remarks/>
        Public AttibuteValue As String
        
        '<remarks/>
        Public RequiredColor As Short
        
        '<remarks/>
        Public ResellerProdCode As String
        
        '<remarks/>
        Public TotalProductCount As String
        
        '<remarks/>
        Public InactiveProductCount As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class GetTicketTextResult
        
        '<remarks/>
        Public ErrorCode As Short
        
        '<remarks/>
        Public ErrorDesc As String
        
        '<remarks/>
        Public TicketText As String
        
        '<remarks/>
        Public TicketTitle As String
        
        '<remarks/>
        Public color As String
        
        '<remarks/>
        Public category As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class Ticket_Info
        
        '<remarks/>
        Public ResellerID As String
        
        '<remarks/>
        Public CustomerID As String
        
        '<remarks/>
        Public OrderID As String
        
        '<remarks/>
        Public RssProdCode As String
        
        '<remarks/>
        Public IsPreActivationProduct As Boolean
        
        '<remarks/>
        Public IsProductActivated As Boolean
        
        '<remarks/>
        Public IsOrderPaid As Boolean
        
        '<remarks/>
        Public TotalProductCount As String
        
        '<remarks/>
        Public InactiveProductCount As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class EnabledServicesResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
End Namespace
