'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
'
Namespace com.infinibiz.webservices
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IBZservicesBinding", [Namespace]:="urn:IBZservices"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(productinfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(rprodsinfo))>  _
    Partial Public Class IBZservices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private addResellerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private updateResellerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private addResellerProductsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private updateResellerProductsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private deleteResellerProductsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getResellerProductsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getResellerM2ProductOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getResellerProductNameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getResellerInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private addPoolProductOperationCompleted As System.Threading.SendOrPostCallback
        
        Private copyResellerProductsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.infinibiz.com/reseller.php"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event addResellerCompleted As addResellerCompletedEventHandler
        
        '''<remarks/>
        Public Event updateResellerCompleted As updateResellerCompletedEventHandler
        
        '''<remarks/>
        Public Event addResellerProductsCompleted As addResellerProductsCompletedEventHandler
        
        '''<remarks/>
        Public Event updateResellerProductsCompleted As updateResellerProductsCompletedEventHandler
        
        '''<remarks/>
        Public Event deleteResellerProductsCompleted As deleteResellerProductsCompletedEventHandler
        
        '''<remarks/>
        Public Event getResellerProductsCompleted As getResellerProductsCompletedEventHandler
        
        '''<remarks/>
        Public Event getResellerM2ProductCompleted As getResellerM2ProductCompletedEventHandler
        
        '''<remarks/>
        Public Event getResellerProductNameCompleted As getResellerProductNameCompletedEventHandler
        
        '''<remarks/>
        Public Event getResellerInfoCompleted As getResellerInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event addPoolProductCompleted As addPoolProductCompletedEventHandler
        
        '''<remarks/>
        Public Event copyResellerProductsCompleted As copyResellerProductsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#addReseller", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function addReseller(ByVal resellerinfo As resellerinfo) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("addReseller", New Object() {resellerinfo})
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Function BeginaddReseller(ByVal resellerinfo As resellerinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("addReseller", New Object() {resellerinfo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndaddReseller(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub addResellerAsync(ByVal resellerinfo As resellerinfo)
            Me.addResellerAsync(resellerinfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addResellerAsync(ByVal resellerinfo As resellerinfo, ByVal userState As Object)
            If (Me.addResellerOperationCompleted Is Nothing) Then
                Me.addResellerOperationCompleted = AddressOf Me.OnaddResellerOperationCompleted
            End If
            Me.InvokeAsync("addReseller", New Object() {resellerinfo}, Me.addResellerOperationCompleted, userState)
        End Sub
        
        Private Sub OnaddResellerOperationCompleted(ByVal arg As Object)
            If (Not (Me.addResellerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent addResellerCompleted(Me, New addResellerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#updateReseller", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function updateReseller(ByVal updateresellerinfo As updateresellerinfo) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("updateReseller", New Object() {updateresellerinfo})
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Function BeginupdateReseller(ByVal updateresellerinfo As updateresellerinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("updateReseller", New Object() {updateresellerinfo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndupdateReseller(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub updateResellerAsync(ByVal updateresellerinfo As updateresellerinfo)
            Me.updateResellerAsync(updateresellerinfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub updateResellerAsync(ByVal updateresellerinfo As updateresellerinfo, ByVal userState As Object)
            If (Me.updateResellerOperationCompleted Is Nothing) Then
                Me.updateResellerOperationCompleted = AddressOf Me.OnupdateResellerOperationCompleted
            End If
            Me.InvokeAsync("updateReseller", New Object() {updateresellerinfo}, Me.updateResellerOperationCompleted, userState)
        End Sub
        
        Private Sub OnupdateResellerOperationCompleted(ByVal arg As Object)
            If (Not (Me.updateResellerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent updateResellerCompleted(Me, New updateResellerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#addResellerProducts", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function addResellerProducts(ByVal addresellprod As addresellprod) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("addResellerProducts", New Object() {addresellprod})
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Function BeginaddResellerProducts(ByVal addresellprod As addresellprod, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("addResellerProducts", New Object() {addresellprod}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndaddResellerProducts(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub addResellerProductsAsync(ByVal addresellprod As addresellprod)
            Me.addResellerProductsAsync(addresellprod, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addResellerProductsAsync(ByVal addresellprod As addresellprod, ByVal userState As Object)
            If (Me.addResellerProductsOperationCompleted Is Nothing) Then
                Me.addResellerProductsOperationCompleted = AddressOf Me.OnaddResellerProductsOperationCompleted
            End If
            Me.InvokeAsync("addResellerProducts", New Object() {addresellprod}, Me.addResellerProductsOperationCompleted, userState)
        End Sub
        
        Private Sub OnaddResellerProductsOperationCompleted(ByVal arg As Object)
            If (Not (Me.addResellerProductsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent addResellerProductsCompleted(Me, New addResellerProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#updateResellerProducts", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function updateResellerProducts(ByVal updateresellprods As updateresellprods) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("updateResellerProducts", New Object() {updateresellprods})
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Function BeginupdateResellerProducts(ByVal updateresellprods As updateresellprods, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("updateResellerProducts", New Object() {updateresellprods}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndupdateResellerProducts(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub updateResellerProductsAsync(ByVal updateresellprods As updateresellprods)
            Me.updateResellerProductsAsync(updateresellprods, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub updateResellerProductsAsync(ByVal updateresellprods As updateresellprods, ByVal userState As Object)
            If (Me.updateResellerProductsOperationCompleted Is Nothing) Then
                Me.updateResellerProductsOperationCompleted = AddressOf Me.OnupdateResellerProductsOperationCompleted
            End If
            Me.InvokeAsync("updateResellerProducts", New Object() {updateresellprods}, Me.updateResellerProductsOperationCompleted, userState)
        End Sub
        
        Private Sub OnupdateResellerProductsOperationCompleted(ByVal arg As Object)
            If (Not (Me.updateResellerProductsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent updateResellerProductsCompleted(Me, New updateResellerProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#deleteResellerProducts", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function deleteResellerProducts(ByVal delresellprods As delresellprods) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("deleteResellerProducts", New Object() {delresellprods})
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Function BegindeleteResellerProducts(ByVal delresellprods As delresellprods, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("deleteResellerProducts", New Object() {delresellprods}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EnddeleteResellerProducts(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub deleteResellerProductsAsync(ByVal delresellprods As delresellprods)
            Me.deleteResellerProductsAsync(delresellprods, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub deleteResellerProductsAsync(ByVal delresellprods As delresellprods, ByVal userState As Object)
            If (Me.deleteResellerProductsOperationCompleted Is Nothing) Then
                Me.deleteResellerProductsOperationCompleted = AddressOf Me.OndeleteResellerProductsOperationCompleted
            End If
            Me.InvokeAsync("deleteResellerProducts", New Object() {delresellprods}, Me.deleteResellerProductsOperationCompleted, userState)
        End Sub
        
        Private Sub OndeleteResellerProductsOperationCompleted(ByVal arg As Object)
            If (Not (Me.deleteResellerProductsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deleteResellerProductsCompleted(Me, New deleteResellerProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#getResellerProducts", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function getResellerProducts(ByVal reselleruid As String) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnResellerProducts
            Dim results() As Object = Me.Invoke("getResellerProducts", New Object() {reselleruid})
            Return CType(results(0),returnResellerProducts)
        End Function
        
        '''<remarks/>
        Public Function BegingetResellerProducts(ByVal reselleruid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getResellerProducts", New Object() {reselleruid}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetResellerProducts(ByVal asyncResult As System.IAsyncResult) As returnResellerProducts
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnResellerProducts)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getResellerProductsAsync(ByVal reselleruid As String)
            Me.getResellerProductsAsync(reselleruid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getResellerProductsAsync(ByVal reselleruid As String, ByVal userState As Object)
            If (Me.getResellerProductsOperationCompleted Is Nothing) Then
                Me.getResellerProductsOperationCompleted = AddressOf Me.OngetResellerProductsOperationCompleted
            End If
            Me.InvokeAsync("getResellerProducts", New Object() {reselleruid}, Me.getResellerProductsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetResellerProductsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getResellerProductsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getResellerProductsCompleted(Me, New getResellerProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#getResellerM2Product", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function getResellerM2Product(ByVal resellerproductcode As resellerproductcode) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnResellerProducts
            Dim results() As Object = Me.Invoke("getResellerM2Product", New Object() {resellerproductcode})
            Return CType(results(0),returnResellerProducts)
        End Function
        
        '''<remarks/>
        Public Function BegingetResellerM2Product(ByVal resellerproductcode As resellerproductcode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getResellerM2Product", New Object() {resellerproductcode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetResellerM2Product(ByVal asyncResult As System.IAsyncResult) As returnResellerProducts
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnResellerProducts)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getResellerM2ProductAsync(ByVal resellerproductcode As resellerproductcode)
            Me.getResellerM2ProductAsync(resellerproductcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getResellerM2ProductAsync(ByVal resellerproductcode As resellerproductcode, ByVal userState As Object)
            If (Me.getResellerM2ProductOperationCompleted Is Nothing) Then
                Me.getResellerM2ProductOperationCompleted = AddressOf Me.OngetResellerM2ProductOperationCompleted
            End If
            Me.InvokeAsync("getResellerM2Product", New Object() {resellerproductcode}, Me.getResellerM2ProductOperationCompleted, userState)
        End Sub
        
        Private Sub OngetResellerM2ProductOperationCompleted(ByVal arg As Object)
            If (Not (Me.getResellerM2ProductCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getResellerM2ProductCompleted(Me, New getResellerM2ProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#getResellerProductName", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function getResellerProductName(ByVal resellerproductcode As resellerproductcode) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnResellerProducts
            Dim results() As Object = Me.Invoke("getResellerProductName", New Object() {resellerproductcode})
            Return CType(results(0),returnResellerProducts)
        End Function
        
        '''<remarks/>
        Public Function BegingetResellerProductName(ByVal resellerproductcode As resellerproductcode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getResellerProductName", New Object() {resellerproductcode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetResellerProductName(ByVal asyncResult As System.IAsyncResult) As returnResellerProducts
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnResellerProducts)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getResellerProductNameAsync(ByVal resellerproductcode As resellerproductcode)
            Me.getResellerProductNameAsync(resellerproductcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getResellerProductNameAsync(ByVal resellerproductcode As resellerproductcode, ByVal userState As Object)
            If (Me.getResellerProductNameOperationCompleted Is Nothing) Then
                Me.getResellerProductNameOperationCompleted = AddressOf Me.OngetResellerProductNameOperationCompleted
            End If
            Me.InvokeAsync("getResellerProductName", New Object() {resellerproductcode}, Me.getResellerProductNameOperationCompleted, userState)
        End Sub
        
        Private Sub OngetResellerProductNameOperationCompleted(ByVal arg As Object)
            If (Not (Me.getResellerProductNameCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getResellerProductNameCompleted(Me, New getResellerProductNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#getResellerInfo", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function getResellerInfo(ByVal reselleruid As String) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnResellerInfo
            Dim results() As Object = Me.Invoke("getResellerInfo", New Object() {reselleruid})
            Return CType(results(0),returnResellerInfo)
        End Function
        
        '''<remarks/>
        Public Function BegingetResellerInfo(ByVal reselleruid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getResellerInfo", New Object() {reselleruid}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetResellerInfo(ByVal asyncResult As System.IAsyncResult) As returnResellerInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnResellerInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getResellerInfoAsync(ByVal reselleruid As String)
            Me.getResellerInfoAsync(reselleruid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getResellerInfoAsync(ByVal reselleruid As String, ByVal userState As Object)
            If (Me.getResellerInfoOperationCompleted Is Nothing) Then
                Me.getResellerInfoOperationCompleted = AddressOf Me.OngetResellerInfoOperationCompleted
            End If
            Me.InvokeAsync("getResellerInfo", New Object() {reselleruid}, Me.getResellerInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OngetResellerInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.getResellerInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getResellerInfoCompleted(Me, New getResellerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#addPoolProduct", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function addPoolProduct(ByVal productinfo As pinfo) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("addPoolProduct", New Object() {productinfo})
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Function BeginaddPoolProduct(ByVal productinfo As pinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("addPoolProduct", New Object() {productinfo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndaddPoolProduct(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub addPoolProductAsync(ByVal productinfo As pinfo)
            Me.addPoolProductAsync(productinfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addPoolProductAsync(ByVal productinfo As pinfo, ByVal userState As Object)
            If (Me.addPoolProductOperationCompleted Is Nothing) Then
                Me.addPoolProductOperationCompleted = AddressOf Me.OnaddPoolProductOperationCompleted
            End If
            Me.InvokeAsync("addPoolProduct", New Object() {productinfo}, Me.addPoolProductOperationCompleted, userState)
        End Sub
        
        Private Sub OnaddPoolProductOperationCompleted(ByVal arg As Object)
            If (Not (Me.addPoolProductCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent addPoolProductCompleted(Me, New addPoolProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#copyResellerProducts", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function copyResellerProducts(ByVal resellers As resellersinfo) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("copyResellerProducts", New Object() {resellers})
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Function BegincopyResellerProducts(ByVal resellers As resellersinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("copyResellerProducts", New Object() {resellers}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndcopyResellerProducts(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub copyResellerProductsAsync(ByVal resellers As resellersinfo)
            Me.copyResellerProductsAsync(resellers, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub copyResellerProductsAsync(ByVal resellers As resellersinfo, ByVal userState As Object)
            If (Me.copyResellerProductsOperationCompleted Is Nothing) Then
                Me.copyResellerProductsOperationCompleted = AddressOf Me.OncopyResellerProductsOperationCompleted
            End If
            Me.InvokeAsync("copyResellerProducts", New Object() {resellers}, Me.copyResellerProductsOperationCompleted, userState)
        End Sub
        
        Private Sub OncopyResellerProductsOperationCompleted(ByVal arg As Object)
            If (Not (Me.copyResellerProductsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent copyResellerProductsCompleted(Me, New copyResellerProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class resellerinfo
        
        Private nameField As String
        
        Private urlField As String
        
        Private renewalurlField As String
        
        Private parentidField As String
        
        Private customeridField As String
        
        Private customeruidField As String
        
        Private emailauthorizedField As String
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property renewalurl() As String
            Get
                Return Me.renewalurlField
            End Get
            Set
                Me.renewalurlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property parentid() As String
            Get
                Return Me.parentidField
            End Get
            Set
                Me.parentidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customerid() As String
            Get
                Return Me.customeridField
            End Get
            Set
                Me.customeridField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customeruid() As String
            Get
                Return Me.customeruidField
            End Get
            Set
                Me.customeruidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property emailauthorized() As String
            Get
                Return Me.emailauthorizedField
            End Get
            Set
                Me.emailauthorizedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class resellersinfo
        
        Private fromresellerField As String
        
        Private toresellerField As String
        
        '''<remarks/>
        Public Property fromreseller() As String
            Get
                Return Me.fromresellerField
            End Get
            Set
                Me.fromresellerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property toreseller() As String
            Get
                Return Me.toresellerField
            End Get
            Set
                Me.toresellerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class pinfo
        
        Private codeField As String
        
        Private nameField As String
        
        Private referrerField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property referrer() As String
            Get
                Return Me.referrerField
            End Get
            Set
                Me.referrerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class getresellerinf
        
        Private nameField As String
        
        Private urlField As String
        
        Private renewalurlField As String
        
        Private customeridField As String
        
        Private emailauthorizedField As String
        
        Private regdateField As String
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property renewalurl() As String
            Get
                Return Me.renewalurlField
            End Get
            Set
                Me.renewalurlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customerid() As String
            Get
                Return Me.customeridField
            End Get
            Set
                Me.customeridField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property emailauthorized() As String
            Get
                Return Me.emailauthorizedField
            End Get
            Set
                Me.emailauthorizedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property regdate() As String
            Get
                Return Me.regdateField
            End Get
            Set
                Me.regdateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class returnResellerInfo
        
        Private eRRORCODEField As Integer
        
        Private eRRORDESCField As String
        
        Private infoField As getresellerinf
        
        '''<remarks/>
        Public Property ERRORCODE() As Integer
            Get
                Return Me.eRRORCODEField
            End Get
            Set
                Me.eRRORCODEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ERRORDESC() As String
            Get
                Return Me.eRRORDESCField
            End Get
            Set
                Me.eRRORDESCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property info() As getresellerinf
            Get
                Return Me.infoField
            End Get
            Set
                Me.infoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class resellerproductcode
        
        Private codesField() As String
        
        Private reselleruidField As String
        
        '''<remarks/>
        Public Property codes() As String()
            Get
                Return Me.codesField
            End Get
            Set
                Me.codesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property reselleruid() As String
            Get
                Return Me.reselleruidField
            End Get
            Set
                Me.reselleruidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class productinfo
        
        Private codeField As String
        
        Private nameField As String
        
        Private resellercodeField As String
        
        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resellercode() As String
            Get
                Return Me.resellercodeField
            End Get
            Set
                Me.resellercodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class returnResellerProducts
        
        Private eRRORCODEField As SByte
        
        Private eRRORDESCField As String
        
        Private productsField() As productinfo
        
        '''<remarks/>
        <CLSCompliant(False)> Public Property ERRORCODE() As SByte
            Get
                Return Me.eRRORCODEField
            End Get
            Set(ByVal value As SByte)
                Me.eRRORCODEField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ERRORDESC() As String
            Get
                Return Me.eRRORDESCField
            End Get
            Set
                Me.eRRORDESCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property products() As productinfo()
            Get
                Return Me.productsField
            End Get
            Set
                Me.productsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class delresellprods
        
        Private codesarrayField() As String
        
        Private customeruidField As String
        
        '''<remarks/>
        Public Property codesarray() As String()
            Get
                Return Me.codesarrayField
            End Get
            Set
                Me.codesarrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customeruid() As String
            Get
                Return Me.customeruidField
            End Get
            Set
                Me.customeruidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class updateresellprods
        
        Private nameField As String
        
        Private codeField As String
        
        Private resellercodeField As String
        
        Private customeruidField As String
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resellercode() As String
            Get
                Return Me.resellercodeField
            End Get
            Set
                Me.resellercodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customeruid() As String
            Get
                Return Me.customeruidField
            End Get
            Set
                Me.customeruidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class rprodsinfo
        
        Private codeField As String
        
        Private nameField As String
        
        Private resellercodeField As String
        
        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resellercode() As String
            Get
                Return Me.resellercodeField
            End Get
            Set
                Me.resellercodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class addresellprod
        
        Private productsField() As rprodsinfo
        
        Private customeruidField As String
        
        '''<remarks/>
        Public Property products() As rprodsinfo()
            Get
                Return Me.productsField
            End Get
            Set
                Me.productsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customeruid() As String
            Get
                Return Me.customeruidField
            End Get
            Set
                Me.customeruidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class updateresellerinfo
        
        Private nameField As String
        
        Private urlField As String
        
        Private renewalurlField As String
        
        Private customeruidField As String
        
        Private emailauthorizedField As String
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property renewalurl() As String
            Get
                Return Me.renewalurlField
            End Get
            Set
                Me.renewalurlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customeruid() As String
            Get
                Return Me.customeruidField
            End Get
            Set
                Me.customeruidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property emailauthorized() As String
            Get
                Return Me.emailauthorizedField
            End Get
            Set
                Me.emailauthorizedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:IBZservices")>  _
    Partial Public Class returnmsg
        
        Private eRRORCODEField As SByte
        
        Private eRRORDESCField As String
        
        '''<remarks/>
        <CLSCompliant(False)>Public Property ERRORCODE() As SByte
            Get
                Return Me.eRRORCODEField
            End Get
            Set
                Me.eRRORCODEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ERRORDESC() As String
            Get
                Return Me.eRRORDESCField
            End Get
            Set
                Me.eRRORDESCField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub addResellerCompletedEventHandler(ByVal sender As Object, ByVal e As addResellerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class addResellerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnmsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnmsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub updateResellerCompletedEventHandler(ByVal sender As Object, ByVal e As updateResellerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class updateResellerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnmsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnmsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub addResellerProductsCompletedEventHandler(ByVal sender As Object, ByVal e As addResellerProductsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class addResellerProductsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnmsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnmsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub updateResellerProductsCompletedEventHandler(ByVal sender As Object, ByVal e As updateResellerProductsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class updateResellerProductsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnmsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnmsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub deleteResellerProductsCompletedEventHandler(ByVal sender As Object, ByVal e As deleteResellerProductsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class deleteResellerProductsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnmsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnmsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub getResellerProductsCompletedEventHandler(ByVal sender As Object, ByVal e As getResellerProductsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getResellerProductsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnResellerProducts
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnResellerProducts)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub getResellerM2ProductCompletedEventHandler(ByVal sender As Object, ByVal e As getResellerM2ProductCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getResellerM2ProductCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnResellerProducts
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnResellerProducts)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub getResellerProductNameCompletedEventHandler(ByVal sender As Object, ByVal e As getResellerProductNameCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getResellerProductNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnResellerProducts
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnResellerProducts)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub getResellerInfoCompletedEventHandler(ByVal sender As Object, ByVal e As getResellerInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getResellerInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnResellerInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnResellerInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub addPoolProductCompletedEventHandler(ByVal sender As Object, ByVal e As addPoolProductCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class addPoolProductCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnmsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnmsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub copyResellerProductsCompletedEventHandler(ByVal sender As Object, ByVal e As copyResellerProductsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class copyResellerProductsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As returnmsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),returnmsg)
            End Get
        End Property
    End Class
End Namespace
